"""agregar_modelos_clinica

Revision ID: 8cb66ac3e4bc
Revises: c1a6027b590f
Create Date: 2026-08-12 15:11:35.831371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb66ac3e4bc'
down_revision: Union[str, Sequence[str], None] = 'c1a6027b590f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_cedula'), 'pacientes', ['cedula'], unique=True)
    op.create_table('procedimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('numero_quirofano', sa.String(length=50), nullable=False),
    sa.Column('fecha_procedimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('retiros_insumos', sa.Column('procedimiento_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_retiros_insumos_id_quirofano'), table_name='retiros_insumos')
    op.create_foreign_key(None, 'retiros_insumos', 'procedimientos', ['procedimiento_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('retiros_insumos', 'id_quirofano')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retiros_insumos', sa.Column('id_quirofano', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'retiros_insumos', type_='foreignkey')
    op.create_index(op.f('ix_retiros_insumos_id_quirofano'), 'retiros_insumos', ['id_quirofano'], unique=False)
    op.drop_column('retiros_insumos', 'procedimiento_id')
    op.drop_table('procedimientos')
    op.drop_index(op.f('ix_pacientes_cedula'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
