"""renombrar_numero_quirofano_a_quirofano

Revision ID: 9ff937c5de2e
Revises: 8cb66ac3e4bc
Create Date: 2026-08-13 19:57:27.024664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff937c5de2e'
down_revision: Union[str, Sequence[str], None] = '8cb66ac3e4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedimientos', sa.Column('quirofano', sa.String(length=50), nullable=False))
    op.drop_column('procedimientos', 'numero_quirofano')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedimientos', sa.Column('numero_quirofano', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('procedimientos', 'quirofano')
    # ### end Alembic commands ###
