"""crear_tablas_iniciales

Revision ID: c1a6027b590f
Revises: 
Create Date: 2026-07-30 22:49:28.339641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a6027b590f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_barras', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=30), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insumos_codigo_barras'), 'insumos', ['codigo_barras'], unique=True)
    op.create_index(op.f('ix_insumos_nombre'), 'insumos', ['nombre'], unique=False)
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_codigo'), 'permisos', ['codigo'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('retiros_insumos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('id_quirofano', sa.String(length=50), nullable=False),
    sa.Column('cantidad_retirada', sa.Integer(), nullable=False),
    sa.Column('fecha_retiro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retiros_insumos_id_quirofano'), 'retiros_insumos', ['id_quirofano'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('devoluciones_insumos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retiro_id', sa.Integer(), nullable=False),
    sa.Column('usuario_recibe_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_devuelta', sa.Integer(), nullable=False),
    sa.Column('estado_insumo', sa.String(length=50), nullable=False),
    sa.Column('fecha_devolucion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['retiro_id'], ['retiros_insumos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_recibe_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devoluciones_insumos')
    op.drop_table('usuario_rol')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_retiros_insumos_id_quirofano'), table_name='retiros_insumos')
    op.drop_table('retiros_insumos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permisos_codigo'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_insumos_nombre'), table_name='insumos')
    op.drop_index(op.f('ix_insumos_codigo_barras'), table_name='insumos')
    op.drop_table('insumos')
    # ### end Alembic commands ###
